#!/bin/bash

cd $(dirname "$0")

# Use conda environment's Python to avoid pyenv interference
if [ -n "$CONDA_PREFIX" ]; then
    $CONDA_PREFIX/bin/python setup.py build_ext --inplace
else
    python setup.py build_ext --inplace
fi
